services:
    interface:
        build: ./interface-service
        image: interface-service
        ports:
            - '8001:80'
            - '5173:5173'
        volumes:
            - './interface-service:/var/www/html'
        networks:
            - interface
            - alegra-services
        depends_on:
            - mysql_interface
    order-manager:
        build: ./order-management-service
        image: order-management-service
        ports:
            - '8002:80'
            - '5174:5173'
        volumes:
            - './order-management-service:/var/www/html'
        networks:
            - order-manager
            - alegra-services
        depends_on:
            - mysql_order_manager
    kitchen:
        build: ./kitchen-service
        image: kitchen-service
        ports:
            - '8003:80'
            - '5175:5173'
        volumes:
            - './kitchen-service:/var/www/html'
        networks:
            - kitchen
            - alegra-services
        depends_on:
            - mysql_kitchen
    store:
        build: ./store-service
        image: store-service
        ports:
            - '8004:80'
            - '5176:5173'
        volumes:
            - './store-service:/var/www/html'
        networks:
            - store
            - alegra-services
        depends_on:
            - mysql_store
    mysql_interface:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-interface-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - interface
    mysql_order_manager:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-order-manager-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - order-manager
    mysql_kitchen:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-kitchen-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - kitchen
    mysql_store:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3309:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-store-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - store
    orders-queue-create-orders:
        image: order-management-service
        command: php /var/www/html/artisan queue:work --queue=CreateOrders --sleep=10 --tries=3
        restart: always
        volumes:
            - './order-management-service:/var/www/html'
        networks:
            - order-manager
        depends_on:
            - mysql_order_manager
            - order-manager
    orders-queue-process-finished-orders:
        image: order-management-service
        command: php /var/www/html/artisan rabbitmq:consume-finished
        restart: on-failure:3
        volumes:
            - './order-management-service:/var/www/html'
        networks:
            - order-manager
        depends_on:
            - mysql_order_manager
            - order-manager
    kitchen-queue-create-plate-orders:
        image: kitchen-service
        command: php /var/www/html/artisan rabbitmq:consume
        restart: on-failure:3
        volumes:
            - './kitchen-service:/var/www/html'
        networks:
            - kitchen
        depends_on:
            - mysql_kitchen
            - kitchen
    kitchen-queue-finished-ingredient-orders:
        image: kitchen-service
        command: php /var/www/html/artisan rabbitmq:consume-finished
        restart: on-failure:3
        volumes:
            - './kitchen-service:/var/www/html'
        networks:
            - kitchen
        depends_on:
            - mysql_kitchen
            - kitchen
    store-process-ingredient-orders:
        image: store-service
        command: php /var/www/html/artisan queue:work --queue=ProcessIngredientOrders --sleep=10 --tries=3
        restart: always
        volumes:
            - './store-service:/var/www/html'
        networks:
            - store
        depends_on:
            - mysql_store
            - store
    store-queue-create-ingredient-orders:
        image: store-service
        command: php /var/www/html/artisan rabbitmq:consume
        restart: on-failure:3
        volumes:
            - './store-service:/var/www/html'
        networks:
            - store
        depends_on:
            - mysql_store
            - store
    store-schedule:
        image: store-service
        command: php /var/www/html/artisan schedule:work
        restart: on-failure:3
        volumes:
            - './store-service:/var/www/html'
        networks:
            - store
        depends_on:
            - mysql_store
            - store
networks:
    interface:
        driver: bridge
    order-manager:
        driver: bridge
    kitchen:
        driver: bridge
    store:
        driver: bridge
    alegra-services:
        driver: bridge
volumes:
    mysql-interface-data:
        driver: local
    mysql-order-manager-data:
        driver: local
    mysql-kitchen-data:
        driver: local
    mysql-store-data:
        driver: local
