services:
    interface:
        build:
            context: ./interface-service
            dockerfile: Dockerfile
        ports:
            - '8001:80'
            - '5173:5173'
        volumes:
            - './interface-service:/var/www/html'
        networks:
            - interface
            - alegra-services
        depends_on:
            - mysql_interface
    order-manager:
        build:
            context: ./order-management-service
            dockerfile: Dockerfile
        ports:
            - '8002:80'
            - '5174:5173'
        volumes:
            - './order-management-service:/var/www/html'
        networks:
            - order-manager
            - alegra-services
        depends_on:
            - mysql_order_manager
    kitchen:
        build:
            context: ./kitchen-service
            dockerfile: Dockerfile
        ports:
            - '8003:80'
            - '5175:5173'
        volumes:
            - './kitchen-service:/var/www/html'
        networks:
            - kitchen
            - alegra-services
        depends_on:
            - mysql_kitchen
    store:
        build:
            context: ./store-service
            dockerfile: Dockerfile
        ports:
            - '8004:80'
            - '5176:5173'
        volumes:
            - './store-service:/var/www/html'
        networks:
            - store
            - alegra-services
        depends_on:
            - mysql_store
    mysql_interface:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-interface-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - interface
    mysql_order_manager:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-order-manager-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - order-manager
    mysql_kitchen:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-kitchen-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - kitchen
    mysql_store:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3309:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-store-data:/var/lib/mysql'
        command: '--socket=/tmp/mysql.sock'
        networks:
            - store
networks:
    interface:
        driver: bridge
    order-manager:
        driver: bridge
    kitchen:
        driver: bridge
    store:
        driver: bridge
    alegra-services:
        driver: bridge
volumes:
    mysql-interface-data:
        driver: local
    mysql-order-manager-data:
        driver: local
    mysql-kitchen-data:
        driver: local
    mysql-store-data:
        driver: local
